export const all_properties = [
    {
      "position": 0,
      "Name": "Payday",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 1,
      "Name": "Red Park",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 5,
      "condo_rent": [ 450, 900, 1350, 1800],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 25,
      "property_type": "Red",
      "property_price": 70,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 2,
      "Name": "Yellow Life Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 3,
      "Name": "Red Road",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 10,
      "condo_rent": [ 500, 1000, 1500, 2000 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 25,
      "property_type": "Red",
      "property_price": 80,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_amount": 0,
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 4,
      "Name": "Tangerine Place",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 10,
      "condo_rent": [ 550, 1100, 1650, 2200],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 50,
      "property_type": "Tangerine",
      "property_price": 90,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 5,
      "Name": "Police Interaction",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 6,
      "Name": "Tangerine Views",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 10,
      "condo_rent": [ 550, 1100, 1650, 2200 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 50,
      "property_type": "Tangerine",
      "property_price": 90,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 7,
      "Name": "Pink Tax",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 8,
      "Name": "Tangerine Towers",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 20,
      "condo_rent": [ 600, 1200, 1800, 2400 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 50,
      "property_type": "Tangerine",
      "property_price": 110,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 9,
      "Name": "Green Life Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 10,
      "Name": "Prison Industrial Complex ",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 11,
      "Name": "Lemon Center",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 20,
      "condo_rent": [ 650, 1300, 1950, 2600 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 100,
      "property_type": "Lemon",
      "property_price": 130,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 12,
      "Name": "Yellow Life Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 13,
      "Name": "Lemon Hill",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 20,
      "condo_rent": [ 650, 1300, 1950, 2600 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 100,
      "property_type": "Lemon",
      "property_price": 130,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 14,
      "Name": "Lemon Lofts",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 25,
      "condo_rent": [ 700, 1400, 2100, 2800 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 100,
      "property_type": "Lemon",
      "property_price": 150,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 15,
      "Name": "Police Interaction",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 16,
      "Name": "Green Lane",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 25,
      "condo_rent": [ 750, 1500, 2250, 3000 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 150,
      "property_type": "Green",
      "property_price": 170,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 17,
      "Name": "Green Live Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 18,
      "Name": "Green Ranch",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 25,
      "condo_rent": [ 750, 1500, 2250, 3000 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 150,
      "property_type": "Green",
      "property_price": 170,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 19,
      "Name": "Green Gardens",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 30,
      "condo_rent": [ 800, 1600, 2400, 3200 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 150,
      "property_type": "Green",
      "property_price": 190,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 20,
      "Name": "Payday"
    },
    {
      "position": 21,
      "Name": "Blue Estates",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 35,
      "condo_rent": [ 850, 1700, 2550, 3400 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 200,
      "property_type": "Blue",
      "property_price": 210,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 22,
      "Name": "Yellow Life Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 23,
      "Name": "Blue Circle",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 35,
      "condo_rent": [ 850, 1700, 2550, 3400 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 200,
      "property_type": "Blue",
      "property_price": 210,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 24,
      "Name": "Blue Boulevard",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 40,
      "condo_rent": [ 900, 1800, 2700, 3600 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 200,
      "property_type": "Blue",
      "property_price": 230,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 25,
      "Name": "Police Interaction",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 26,
      "Name": "Indigo Terrace",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 45,
      "condo_rent": [ 950, 1900, 2850, 3800 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 250,
      "property_type": "Indigo",
      "property_price": 250,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 27,
      "Name": "Indigo Estates",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 45,
      "condo_rent": [ 950, 1900, 2850, 3800 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 250,
      "property_type": "Indigo",
      "property_price": 250,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 28,
      "Name": "Green Life Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 29,
      "Name": "Indigo International",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 50,
      "condo_rent": [ 1000, 2000, 3000, 4000 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 250,
      "property_type": "Indigo",
      "property_price": 270,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 30,
      "Name": "Jackpot",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 31,
      "Name": "Violet Plaza",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 50,
      "condo_rent": [ 1050, 2100, 3150, 4200 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 300,
      "property_type": "Violet",
      "property_price": 290,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 32,
      "Name": "Violet Castles",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 50,
      "condo_rent": [ 1050, 2100, 3150, 4200 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 300,
      "property_type": "Violet",
      "property_price": 290,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 33,
      "Name": "Yellow Life Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 34,
      "Name": "Violet Villa",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 55,
      "condo_rent": [ 1100, 2200, 3300, 4400 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 300,
      "property_type": "Violet",
      "property_price": 310,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 35,
      "Name": "Utilities",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 36,
      "Name": "Pink Manor",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 55,
      "condo_rent": [ 1500, 3000, 4500, 6000 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 350,
      "property_type": "Pink",
      "property_price": 375,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    },
    {
      "position": 37,
      "Name": "Green Life Event",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 38,
      "Name": "Entrepreneurship",
      "player_id": 0,
      "player_name": "",
      "player_color": ""
    },
    {
      "position": 39,
      "Name": "Pink Palace",
      "is_sale": 0,
      "is_mortgage": 0,
      "rent": 60,
      "condo_rent": [ 2000, 4000, 6000, 8000 ],
      "maximum_condo": 4,
      "number_of_condo": 0,
      "condo_fee": 350,
      "property_type": "Pink",
      "property_price": 425,
      "player_id": 0,
      "player_name": "",
      "player_color": "",
      "bidder_status": 0,
      "bidder_player_position": []
    }
  ] 