export const identity_assets =
[
    [
        { "name":"Inheritance", "value":"Roll less than 9 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 12 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $235" },
        { "name":"Promotion", "value":"Roll less than 10 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 11 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $50" },
        { "name":"Voting", "value":"Roll less than 8 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 11 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 11 to own" },
        { "name":"Insurance", "value":"Roll less than 10 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 11 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $100 and Odd for pay $50" },
    ],
    [
        { "name":"Inheritance", "value":"Roll less than 6 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 6 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $145" },
        { "name":"Promotion", "value":"Roll less than 9 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 6 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $75" },
        { "name":"Voting", "value":"Roll less than 6 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 8 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 6 to own" },
        { "name":"Insurance", "value":"Roll less than 8 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 6 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $100 and Odd for pay $150" },
    ],
    [
        { "name":"Inheritance", "value":"Roll less than 7 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 9 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $140" },
        { "name":"Promotion", "value":"Roll less than 9 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 7 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $75" },
        { "name":"Voting", "value":"Roll less than 7 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 8 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 7 to own" },
        { "name":"Insurance", "value":"Roll less than 7 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 9 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $350 and Odd for pay $150" },
    ],
    [
        { "name":"Inheritance", "value":"Roll less than 11 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 10 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $200" },
        { "name":"Promotion", "value":"Roll less than 12 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 9 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $50" },
        { "name":"Voting", "value":"Roll less than 9 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 12 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 9 to own" },
        { "name":"Insurance", "value":"Roll less than 11 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 9 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $700 and Odd for receive $150" },
    ],
    [
        { "name":"Inheritance", "value":"Roll less than 9 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 12 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $175" },
        { "name":"Promotion", "value":"Roll less than 10 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 11 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $50" },
        { "name":"Voting", "value":"Roll less than 11 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 11 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 11 to own" },
        { "name":"Insurance", "value":"Roll less than 10 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 10 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $100 and Odd for pay $50" },
    ],
    [
        { "name":"Inheritance", "value":"Roll less than 6 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 7 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $130" },
        { "name":"Promotion", "value":"Roll less than 7 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 9 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $75" },
        { "name":"Voting", "value":"Roll less than 9 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 8 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 6 to own" },
        { "name":"Insurance", "value":"Roll less than 8 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 5 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $100 and Odd for pay $50" },
    ],
    [
        { "name":"Inheritance", "value":"Roll less than 7 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 8 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $115" },
        { "name":"Promotion", "value":"Roll less than 7 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 9 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $75" },
        { "name":"Voting", "value":"Roll less than 9 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 8 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 7 to own" },
        { "name":"Insurance", "value":"Roll less than 7 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 8 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $350 and Odd for pay $150" },
    ],
    [
        { "name":"Inheritance", "value":"Roll less than 11 to receive inheritance" },
        { "name":"Employment", "value":"Roll less than 11 to become employed" },
        { "name":"Salary", "value":"Receive a base salary of $165" },
        { "name":"Promotion", "value":"Roll less than 11 to receive a promotion" },
        { "name":"Prison Industrial", "value":"Roll less than 12 to avoid a P.I.C" },
        { "name":"Bail", "value":"Pay $50" },
        { "name":"Voting", "value":"Roll less than 12 to keep right to vote" },
        { "name":"Mortgage", "value":"Roll less than 12 to get approval" },
        { "name":"Entrepreneurship", "value":"Roll less than 9 to own" },
        { "name":"Insurance", "value":"Roll less than 11 to receive health insurance" },
        { "name":"Violence", "value":"Roll less than 7 to avoid intimate partner violence" },
        { "name":"Disaster", "value":"Event for receive $700 and Odd for receive $150" },
    ],
]  